In [6]:
import os
import hashlib
from pathlib import Path
import pandas as pd
import langid
import psycopg
from src.pipeline.load_ingest_to_db import (
    detect_lang, hash_url, hash_text500,
    scan_tree, domain_expr, insert_polars_to_postgres
)
from src.config import get_settings
import json
from urllib.parse import urlsplit
import polars as pl

('reuters.com',
 'bbc.com',
 'bbc.co.uk',
 'ft.com',
 'bloomberg.com',
 'cnbc.com',
 'wsj.com',
 'nytimes.com',
 'economist.com',
 'theguardian.com',
 'washingtonpost.com',
 'apnews.com',
 'businessinsider.com',
 'marketwatch.com',
 'yahoo.com',
 'forbes.com',
 'cnn.com',
 'nbcnews.com',
 'abcnews.go.com',
 'aljazeera.com',
 'www.channelnewsasia.com',
 'www.thenationalnews.com',
 'www.straitstimes.com',
 'vietnamnews.vn',
 'abcnews.go.com',
 'www.cbsnews.com',
 'www.foxnews.com',
 'www.latimes.com',
 'globalnews.ca',
 'www.ctvnews.ca',
 'www.telegraph.co.uk',
 'www.independent.co.uk',
 'www.the-independent.com',
 'www.irishtimes.com',
 'www.scotsman.com',
 'www.yorkshirepost.co.uk',
 'indianexpress.com',
 'www.ndtv.com',
 'gulfnews.com',
 'www.khaleejtimes.com',
 'allafrica.com',
 'www.timeslive.co.za',
 'www.businesslive.co.za',
 'thewest.com.au',
 'www.nzherald.co.nz',
 'qz.com',
 'www.tass.ru',
 'www.interfax.ru',
 'www.rbc.ru',
 'www.vedomosti.ru',
 'www.kommersant.ru',
 'www.lenta.ru',
 'www.nur.kz',
 'www.zakon.kz')

In [8]:
BASE_DIR = Path.cwd().parent
RAW_DIR = BASE_DIR / "data" / "raw"

CC_DIR = RAW_DIR / "ccnews"
RSS_DIR = RAW_DIR / "rss"
ALL_NEWS_DIR = RAW_DIR / "rjac__all-the-news-2-1-Component-one"

with open(BASE_DIR / 'src/config.json', 'r') as f:
    config = json.load(f)
allowed_domains = get_settings().allowed_domains
allowed_domains

('reuters.com',
 'bbc.com',
 'bbc.co.uk',
 'ft.com',
 'bloomberg.com',
 'cnbc.com',
 'wsj.com',
 'nytimes.com',
 'economist.com',
 'theguardian.com',
 'washingtonpost.com',
 'apnews.com',
 'businessinsider.com',
 'marketwatch.com',
 'yahoo.com',
 'forbes.com',
 'cnn.com',
 'nbcnews.com',
 'abcnews.go.com',
 'aljazeera.com',
 'www.channelnewsasia.com',
 'www.thenationalnews.com',
 'www.straitstimes.com',
 'vietnamnews.vn',
 'abcnews.go.com',
 'www.cbsnews.com',
 'www.foxnews.com',
 'www.latimes.com',
 'globalnews.ca',
 'www.ctvnews.ca',
 'www.telegraph.co.uk',
 'www.independent.co.uk',
 'www.the-independent.com',
 'www.irishtimes.com',
 'www.scotsman.com',
 'www.yorkshirepost.co.uk',
 'indianexpress.com',
 'www.ndtv.com',
 'gulfnews.com',
 'www.khaleejtimes.com',
 'allafrica.com',
 'www.timeslive.co.za',
 'www.businesslive.co.za',
 'thewest.com.au',
 'www.nzherald.co.nz',
 'qz.com',
 'www.tass.ru',
 'www.interfax.ru',
 'www.rbc.ru',
 'www.vedomosti.ru',
 'www.kommersant.ru',
 'www.lenta.ru',
 'www.nur.kz',
 'www.zakon.kz')

In [9]:
cc = (
    scan_tree(CC_DIR)
    .with_columns(
        pl.col("url")
        .cast(pl.Utf8)
        .str.extract(r"^(?:https?://)?(?:www\.)?([^/]+)", 1)
        .str.to_lowercase()
        .alias("domain")
    )
    .filter(
        pl.any_horizontal(
            [pl.col("url").str.contains(d, literal=True) for d in allowed_domains]
        )
    )
    .select([
        pl.lit("ccnews_manual").alias("source_type"),
        pl.col("domain"),
        pl.col("title").cast(pl.Utf8),
        pl.col("url").cast(pl.Utf8),
        pl.col("date").str.to_datetime(strict=False).alias("datetime"),
        pl.col("author").cast(pl.Utf8),
        pl.col("lang").cast(pl.Utf8),
        pl.col("text").cast(pl.Utf8),
    ])
)

In [10]:
cc.fetch(100)

/var/folders/2m/29xtnqfj03nf_9dt_g1d04d40000gn/T/ipykernel_67742/1807046244.py:1: DeprecationWarning: `LazyFrame.fetch` is deprecated; use `LazyFrame.collect` instead, in conjunction with a call to `head`.
  cc.fetch(100)

shape: (100, 8)
┌─────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬──────┬────────────┐
│ source_type ┆ domain     ┆ title      ┆ url        ┆ datetime   ┆ author     ┆ lang ┆ text       │
│ ---         ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---  ┆ ---        │
│ str         ┆ str        ┆ str        ┆ str        ┆ datetime[μ ┆ str        ┆ str  ┆ str        │
│             ┆            ┆            ┆            ┆ s]         ┆            ┆      ┆            │
╞═════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪══════╪════════════╡
│ ccnews_manu ┆ interfax.r ┆ Энергоблок ┆ https://ww ┆ 2025-01-01 ┆ null       ┆ ru   ┆ Энергоблок │
│ al          ┆ u          ┆ №7 Нововор ┆ w.interfax ┆ 00:00:00   ┆            ┆      ┆ №7 Нововор │
│             ┆            ┆ онежской … ┆ .ru/russia ┆            ┆            ┆      ┆ онежской … │
│             ┆            ┆            ┆ …          ┆            ┆            ┆      ┆            │
│ ccnews_manu ┆ interfax.r ┆ Минобороны ┆ https://ww ┆ 2025-01-01 ┆ null       ┆ ru   ┆ Минобороны │
│ al          ┆ u          ┆ заявило о  ┆ w.interfax ┆ 00:00:00   ┆            ┆      ┆ заявило о  │
│             ┆            ┆ нейтрализ… ┆ .ru/russia ┆            ┆            ┆      ┆ нейтрализ… │
│             ┆            ┆            ┆ …          ┆            ┆            ┆      ┆            │
│ ccnews_manu ┆ interfax.r ┆ ФБР разыск ┆ https://ww ┆ 2025-01-01 ┆ null       ┆ ru   ┆ ФБР разыск │
│ al          ┆ u          ┆ ивает      ┆ w.interfax ┆ 00:00:00   ┆            ┆      ┆ ивает      │
│             ┆            ┆ возможных  ┆ .ru/world/ ┆            ┆            ┆      ┆ возможных  │
│             ┆            ┆ сооб…      ┆ …          ┆            ┆            ┆      ┆ сооб…      │
│ ccnews_manu ┆ interfax.r ┆ Что        ┆ https://ww ┆ 2025-01-01 ┆ null       ┆ ru   ┆ Что        │
│ al          ┆ u          ┆ произошло  ┆ w.interfax ┆ 00:00:00   ┆            ┆      ┆ произошло  │
│             ┆            ┆ за день:   ┆ .ru/world/ ┆            ┆            ┆      ┆ за день:   │
│             ┆            ┆ среда, …   ┆ …          ┆            ┆            ┆      ┆ среда, …   │
│ ccnews_manu ┆ allafrica. ┆ Rwanda's   ┆ https://al ┆ 2025-01-01 ┆ Peter      ┆ en   ┆ Over 100   │
│ al          ┆ com        ┆ First Ever ┆ lafrica.co ┆ 00:00:00   ┆ Kamasa     ┆      ┆ internatio │
│             ┆            ┆ Multi-Stag ┆ m/stories/ ┆            ┆            ┆      ┆ nal        │
│             ┆            ┆ …          ┆ …          ┆            ┆            ┆      ┆ runners…   │
│ …           ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …    ┆ …          │
│ ccnews_manu ┆ kommersant ┆ Строительс ┆ https://ww ┆ 2025-01-01 ┆ Наталья    ┆ ru   ┆ Строительс │
│ al          ┆ .ru        ┆ тво трассы ┆ w.kommersa ┆ 00:00:00   ┆ Решетняк   ┆      ┆ тво трассы │
│             ┆            ┆ между Кис… ┆ nt.ru/doc/ ┆            ┆            ┆      ┆ между Кис… │
│             ┆            ┆            ┆ …          ┆            ┆            ┆      ┆            │
│ ccnews_manu ┆ rbc.ru     ┆ В России   ┆ https://ww ┆ 2025-01-01 ┆ Фото       ┆ ru   ┆ В России   │
│ al          ┆            ┆ введут     ┆ w.rbc.ru/r ┆ 00:00:00   ┆ Виталий    ┆      ┆ введут     │
│             ┆            ┆ единый     ┆ bcfreenews ┆            ┆ Аньков;    ┆      ┆ единый     │
│             ┆            ┆ экзамен…   ┆ …          ┆            ┆ РИА Новос… ┆      ┆ экзамен…   │
│ ccnews_manu ┆ rbc.ru     ┆ Россиян    ┆ https://ww ┆ 2025-01-01 ┆ Фото       ┆ ru   ┆ Россиян    │
│ al          ┆            ┆ предупреди ┆ w.rbc.ru/r ┆ 00:00:00   ┆ Сергей     ┆      ┆ предупреди │
│             ┆            ┆ ли о       ┆ bcfreenews ┆            ┆ Киселев;   ┆      ┆ ли о       │
│             ┆            ┆ вирусе …   ┆ …          ┆            ┆ АГН «Моск… ┆      ┆ вирусе …   │
│ ccnews_manu ┆ rbc.ru     ┆ Как        ┆ https://ww ┆ 2025-01-01 ┆ null       ┆ ru   ┆ Как        │
│ al          ┆            ┆ выглядит   ┆ w.rbc.ru/r ┆ 00:00:00   ┆            ┆      ┆ выглядит   │
│             ┆            ┆ потерпевши ┆ bcfreenews ┆            ┆            ┆      ┆ потерпевши │
│             ┆            ┆ й круше…   ┆ …          ┆            ┆            ┆      ┆ й круше…   │
│ ccnews_manu ┆ rbc.ru     ┆ На кузове  ┆ https://ww ┆ 2025-01-01 ┆ Фото       ┆ ru   ┆ На кузове  │
│ al          ┆            ┆ машины вре ┆ w.rbc.ru/r ┆ 00:00:00   ┆ Michael    ┆      ┆ машины вре │
│             ┆            ┆ завшегося  ┆ bcfreenews ┆            ┆ DeMocker;  ┆      ┆ завшегося  │
│             ┆            ┆ …          ┆ …          ┆            ┆ Getty I…   ┆      ┆ …          │
└─────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴──────┴────────────┘

In [11]:
cc.collect().height

621924

In [18]:
rss = (
    scan_tree(RSS_DIR)
    .select([
        pl.lit("rss").alias("source_type"),
        domain_expr("url"),
        pl.col("title").cast(pl.Utf8),
        pl.col("url").cast(pl.Utf8),
        pl.col("date").str.to_datetime(strict=False).alias("datetime"),
        pl.col("author").cast(pl.Utf8),
        pl.col("lang").cast(pl.Utf8),
        pl.col("text").cast(pl.Utf8),
    ])
)

In [19]:
rss.fetch(100)

/var/folders/2m/29xtnqfj03nf_9dt_g1d04d40000gn/T/ipykernel_33549/2992771579.py:1: DeprecationWarning: `LazyFrame.fetch` is deprecated; use `LazyFrame.collect` instead, in conjunction with a call to `head`.
  rss.fetch(100)

shape: (22, 8)
┌─────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬──────┬────────────┐
│ source_type ┆ domain     ┆ title      ┆ url        ┆ datetime   ┆ author     ┆ lang ┆ text       │
│ ---         ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---  ┆ ---        │
│ str         ┆ str        ┆ str        ┆ str        ┆ datetime[μ ┆ str        ┆ str  ┆ str        │
│             ┆            ┆            ┆            ┆ s]         ┆            ┆      ┆            │
╞═════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪══════╪════════════╡
│ rss         ┆ aljazeera. ┆ UK-led     ┆ https://ww ┆ 2026-04-02 ┆ Al Jazeera ┆ en   ┆ UK-led     │
│             ┆ com        ┆ coalition  ┆ w.aljazeer ┆ 00:00:00   ┆ Staff      ┆      ┆ coalition  │
│             ┆            ┆ of 40      ┆ a.com/news ┆            ┆            ┆      ┆ of 40      │
│             ┆            ┆ countri…   ┆ …          ┆            ┆            ┆      ┆ countri…   │
│ rss         ┆ aljazeera. ┆ Pakistan   ┆ https://ww ┆ 2026-04-02 ┆ Abid       ┆ en   ┆ Pakistan   │
│             ┆ com        ┆ to         ┆ w.aljazeer ┆ 00:00:00   ┆ Hussain    ┆      ┆ to         │
│             ┆            ┆ continue   ┆ a.com/news ┆            ┆            ┆      ┆ continue   │
│             ┆            ┆ with Iran… ┆ …          ┆            ┆            ┆      ┆ with Iran… │
│ rss         ┆ aljazeera. ┆ ‘Bomb back ┆ https://ww ┆ 2026-04-02 ┆ Sarah      ┆ en   ┆ ‘Bomb back │
│             ┆ com        ┆ to the     ┆ w.aljazeer ┆ 00:00:00   ┆ Shamim     ┆      ┆ to the     │
│             ┆            ┆ Stone      ┆ a.com/news ┆            ┆            ┆      ┆ Stone      │
│             ┆            ┆ Age’: …    ┆ …          ┆            ┆            ┆      ┆ Age’: …    │
│ rss         ┆ aljazeera. ┆ Women’s    ┆ https://ww ┆ 2026-04-02 ┆ AFP        ┆ en   ┆ Women’s    │
│             ┆ com        ┆ Asian Cup  ┆ w.aljazeer ┆ 00:00:00   ┆            ┆      ┆ Asian Cup  │
│             ┆            ┆ finalists  ┆ a.com/spor ┆            ┆            ┆      ┆ finalists  │
│             ┆            ┆ ac…        ┆ …          ┆            ┆            ┆      ┆ ac…        │
│ rss         ┆ aljazeera. ┆ Four       ┆ https://ww ┆ 2026-04-02 ┆ Al Jazeera ┆ en   ┆ Four       │
│             ┆ com        ┆ children   ┆ w.aljazeer ┆ 00:00:00   ┆ Staff      ┆      ┆ children   │
│             ┆            ┆ killed in  ┆ a.com/news ┆            ┆            ┆      ┆ killed in  │
│             ┆            ┆ nurser…    ┆ …          ┆            ┆            ┆      ┆ nurser…    │
│ …           ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …    ┆ …          │
│ rss         ┆ aljazeera. ┆ Iran’s     ┆ https://ww ┆ 2026-04-02 ┆ Al Jazeera ┆ en   ┆ Iran’s     │
│             ┆ com        ┆ ex-foreign ┆ w.aljazeer ┆ 00:00:00   ┆ Staff      ┆      ┆ ex-foreign │
│             ┆            ┆ minister   ┆ a.com/news ┆            ┆            ┆      ┆ minister   │
│             ┆            ┆ Kha…       ┆ …          ┆            ┆            ┆      ┆ Kha…       │
│ rss         ┆ aljazeera. ┆ Oil price  ┆ https://ww ┆ 2026-04-02 ┆ Al Jazeera ┆ en   ┆ Oil price  │
│             ┆ com        ┆ surges,    ┆ w.aljazeer ┆ 00:00:00   ┆ Staff      ┆      ┆ surges,    │
│             ┆            ┆ Asian      ┆ a.com/news ┆            ┆            ┆      ┆ Asian      │
│             ┆            ┆ stocks…    ┆ …          ┆            ┆            ┆      ┆ stocks…    │
│ rss         ┆ aljazeera. ┆ Iran war:  ┆ https://ww ┆ 2026-04-02 ┆ Elizabeth  ┆ en   ┆ EXPLAINER  │
│             ┆ com        ┆ What is    ┆ w.aljazeer ┆ 00:00:00   ┆ Melimopoul ┆      ┆ Iran war:  │
│             ┆            ┆ happening  ┆ a.com/news ┆            ┆ os         ┆      ┆ What is    │
│             ┆            ┆ on…        ┆ …          ┆            ┆            ┆      ┆ ha…        │
│ rss         ┆ aljazeera. ┆ Mourners   ┆ https://ww ┆ 2026-04-02 ┆ Al         ┆ en   ┆ In         │
│             ┆ com        ┆ vow        ┆ w.aljazeer ┆ 00:00:00   ┆ Jazeera;   ┆      ┆ Pictures   │
│             ┆            ┆ resistance ┆ a.com/gall ┆            ┆ AFP        ┆      ┆ Mourners   │
│             ┆            ┆ as Ira…    ┆ …          ┆            ┆            ┆      ┆ vow resis… │
│ rss         ┆ aljazeera. ┆ ‘It all    ┆ https://ww ┆ 2026-04-02 ┆ Sajad      ┆ en   ┆ ‘It all    │
│             ┆ com        ┆ depends on ┆ w.aljazeer ┆ 00:00:00   ┆ Hameed;    ┆      ┆ depends on │
│             ┆            ┆ the crop’: ┆ a.com/econ ┆            ┆ Rehan      ┆      ┆ the crop’: │
│             ┆            ┆ …          ┆ …          ┆            ┆ Qayoom Mir ┆      ┆ …          │
└─────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴──────┴────────────┘

In [ ]:
all_news = (
    scan_tree(ALL_NEWS_DIR)
    .filter(pl.col("url").is_not_null())
    .select([
        pl.lit("all_the_news").alias("source_type"),
        domain_expr("url"),
        pl.col("title").cast(pl.Utf8),
        pl.col("url").cast(pl.Utf8),
        pl.col("date").str.to_datetime(strict=False).alias("datetime"),
        pl.col("author").cast(pl.Utf8),
        pl.lit("en").alias("lang"),             
        pl.col("article").cast(pl.Utf8).alias("text"),  
    ])
)

In [21]:
all_news.fetch(100)

/var/folders/2m/29xtnqfj03nf_9dt_g1d04d40000gn/T/ipykernel_33549/2068405862.py:1: DeprecationWarning: `LazyFrame.fetch` is deprecated; use `LazyFrame.collect` instead, in conjunction with a call to `head`.
  all_news.fetch(100)

shape: (100, 8)
┌─────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬──────┬────────────┐
│ source_type ┆ domain     ┆ title      ┆ url        ┆ datetime   ┆ author     ┆ lang ┆ text       │
│ ---         ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---  ┆ ---        │
│ str         ┆ str        ┆ str        ┆ str        ┆ datetime[μ ┆ str        ┆ str  ┆ str        │
│             ┆            ┆            ┆            ┆ s]         ┆            ┆      ┆            │
╞═════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪══════╪════════════╡
│ all_the_new ┆ vox.com    ┆ We should  ┆ https://ww ┆ 2016-12-09 ┆ Lee        ┆ en   ┆ This post  │
│ s           ┆            ┆ take       ┆ w.vox.com/ ┆ 18:31:00   ┆ Drutman    ┆      ┆ is part of │
│             ┆            ┆ concerns   ┆ polyarchy/ ┆            ┆            ┆      ┆ Polyarchy… │
│             ┆            ┆ about …    ┆ …          ┆            ┆            ┆      ┆            │
│ all_the_new ┆ businessin ┆ Colts GM   ┆ https://ww ┆ 2016-10-07 ┆ Scott      ┆ en   ┆ The Indian │
│ s           ┆ sider.com  ┆ Ryan       ┆ w.business ┆ 21:26:46   ┆ Davis      ┆      ┆ apolis     │
│             ┆            ┆ Grigson    ┆ insider.co ┆            ┆            ┆      ┆ Colts made │
│             ┆            ┆ says And…  ┆ …          ┆            ┆            ┆      ┆ A…         │
│ all_the_new ┆ reuters.co ┆ Trump      ┆ https://ww ┆ 2018-01-26 ┆ null       ┆ en   ┆ DAVOS, Swi │
│ s           ┆ m          ┆ denies     ┆ w.reuters. ┆ 00:00:00   ┆            ┆      ┆ tzerland   │
│             ┆            ┆ report he  ┆ com/articl ┆            ┆            ┆      ┆ (Reuters)  │
│             ┆            ┆ ordered…   ┆ …          ┆            ┆            ┆      ┆ -…         │
│ all_the_new ┆ reuters.co ┆ France's   ┆ https://ww ┆ 2019-06-27 ┆ null       ┆ en   ┆ PARIS      │
│ s           ┆ m          ┆ Sarkozy    ┆ w.reuters. ┆ 00:00:00   ┆            ┆      ┆ (Reuters)  │
│             ┆            ┆ reveals    ┆ com/articl ┆            ┆            ┆      ┆ - Former   │
│             ┆            ┆ his '…     ┆ …          ┆            ┆            ┆      ┆ Frenc…     │
│ all_the_new ┆ tmz.com    ┆ Paris      ┆ https://ww ┆ 2016-01-27 ┆ null       ┆ en   ┆ Paris      │
│ s           ┆            ┆ Hilton:    ┆ w.tmz.com/ ┆ 00:00:00   ┆            ┆      ┆ Hilton     │
│             ┆            ┆ Woman In   ┆ 2016/01/27 ┆            ┆            ┆      ┆ arrived at │
│             ┆            ┆ Black F…   ┆ …          ┆            ┆            ┆      ┆ LAX We…    │
│ …           ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …    ┆ …          │
│ all_the_new ┆ reuters.co ┆ Switzerlan ┆ https://ww ┆ 2019-06-26 ┆ null       ┆ en   ┆ ZURICH,    │
│ s           ┆ m          ┆ d's Softwa ┆ w.reuters. ┆ 00:00:00   ┆            ┆      ┆ June 26    │
│             ┆            ┆ reONE      ┆ com/articl ┆            ┆            ┆      ┆ (Reuters)  │
│             ┆            ┆ mand…      ┆ …          ┆            ┆            ┆      ┆ - Sw…      │
│ all_the_new ┆ vox.com    ┆ Where the  ┆ https://ww ┆ 2017-09-26 ┆ Rani Molla ┆ en   ┆ Software   │
│ s           ┆            ┆ software   ┆ w.vox.com/ ┆ 09:00:02   ┆            ┆      ┆ companies  │
│             ┆            ┆ industry   ┆ 2017/9/26/ ┆            ┆            ┆      ┆ are        │
│             ┆            ┆ is…        ┆ …          ┆            ┆            ┆      ┆ contrib…   │
│ all_the_new ┆ tmz.com    ┆ Will Smith ┆ https://ww ┆ 2019-05-27 ┆ null       ┆ en   ┆ Will Smith │
│ s           ┆            ┆ Secretly   ┆ w.tmz.com/ ┆ 00:00:00   ┆            ┆      ┆ is one of  │
│             ┆            ┆ Watches    ┆ 2019/05/27 ┆            ┆            ┆      ┆ the bigge… │
│             ┆            ┆ 'A…        ┆ …          ┆            ┆            ┆      ┆            │
│ all_the_new ┆ tmz.com    ┆ TMZ Live   ┆ https://ww ┆ 2018-04-20 ┆ null       ┆ en   ┆ HERE'S THE │
│ s           ┆            ┆ Cardi B &  ┆ w.tmz.com/ ┆ 00:00:00   ┆            ┆      ┆ RUNDOWNTri │
│             ┆            ┆ Bernie     ┆ 2018/04/20 ┆            ┆            ┆      ┆ stan Thom… │
│             ┆            ┆ Sand…      ┆ …          ┆            ┆            ┆      ┆            │
│ all_the_new ┆ vox.com    ┆ More than  ┆ https://ww ┆ 2017-12-22 ┆ Anna North ┆ en   ┆ Harvey     │
│ s           ┆            ┆ 50 people  ┆ w.vox.com/ ┆ 18:50:02   ┆            ┆      ┆ Weinstein  │
│             ┆            ┆ have       ┆ identities ┆            ┆            ┆      ┆ has been   │
│             ┆            ┆ faced…     ┆ …          ┆            ┆            ┆      ┆ fire…      │
└─────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴──────┴────────────┘

In [22]:
all_news.collect().height

2676301

In [24]:
df = (
    pl.concat([cc, rss, all_news], how="diagonal_relaxed")
    .filter(
        pl.col("url").is_not_null() &
        pl.col("text").is_not_null() &
        (pl.col("url").str.len_chars() > 0) &
        (pl.col("text").str.len_chars() > 0)
    )
    .with_columns([
        pl.col("url")
            .cast(pl.Utf8)
            .map_elements(lambda s: hashlib.sha256(s.encode("utf-8")).hexdigest(), return_dtype=pl.Utf8)
            .alias("article_id"),
        (
            pl.col("text")
            .str.to_lowercase()
            .str.strip_chars()
            .str.slice(0, 500)
            .map_elements(lambda s: hashlib.sha256(s.encode("utf-8")).hexdigest(), return_dtype=pl.Utf8)
            .cast(pl.Utf8)
            .alias("text_hash")
        )
    ])
    .unique(subset=["article_id"], keep="first")
    .unique(subset=["text_hash"], keep="first")
    .collect(streaming=True)
)

print(df.shape)
df.head()

/var/folders/2m/29xtnqfj03nf_9dt_g1d04d40000gn/T/ipykernel_33549/1728981508.py:26: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  .collect(streaming=True)

(3029818, 10)

shape: (5, 10)
┌────────────┬────────────┬────────────┬────────────┬───┬──────┬───────────┬───────────┬───────────┐
│ source_typ ┆ domain     ┆ title      ┆ url        ┆ … ┆ lang ┆ text      ┆ article_i ┆ text_hash │
│ e          ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---  ┆ ---       ┆ d         ┆ ---       │
│ ---        ┆ str        ┆ str        ┆ str        ┆   ┆ str  ┆ str       ┆ ---       ┆ str       │
│ str        ┆            ┆            ┆            ┆   ┆      ┆           ┆ str       ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════╪═══════════╪═══════════╪═══════════╡
│ all_the_ne ┆ cnbc.com   ┆ German     ┆ https://ww ┆ … ┆ en   ┆ BERLIN,   ┆ 6a7292ec9 ┆ 4100edb3f │
│ ws         ┆            ┆ exports to ┆ w.cnbc.com ┆   ┆      ┆ Aug 12    ┆ 0a5449a92 ┆ 044b80f3e │
│            ┆            ┆ Iran halve ┆ /2019/08/1 ┆   ┆      ┆ (Reuters) ┆ 75caa198f ┆ 8cbb319ac │
│            ┆            ┆ i…         ┆ …          ┆   ┆      ┆ - Ger…    ┆ 8ed…      ┆ 234…      │
│ all_the_ne ┆ foxnews.co ┆ Democratic ┆ https://ww ┆ … ┆ en   ┆           ┆ 53c8673ca ┆ ff9d04996 │
│ ws         ┆ m          ┆ women in   ┆ w.foxnews. ┆   ┆      ┆ Senator   ┆ 116c89174 ┆ a67b82164 │
│            ┆            ┆ the        ┆ com/opinio ┆   ┆      ┆ Elizabeth ┆ 43ea20185 ┆ 5857dee0b │
│            ┆            ┆ Senate…    ┆ …          ┆   ┆      ┆ W…        ┆ f0c…      ┆ 952…      │
│ all_the_ne ┆ cnbc.com   ┆ Blockchain ┆ https://ww ┆ … ┆ en   ┆ July 30   ┆ d882667a5 ┆ 1fa8bf303 │
│ ws         ┆            ┆ launches   ┆ w.cnbc.com ┆   ┆      ┆ (Reuters) ┆ 01c72c007 ┆ fe5dfaf3a │
│            ┆            ┆ cryptocurr ┆ /2019/07/3 ┆   ┆      ┆ - Blockch ┆ 298faec5d ┆ d59d2895b │
│            ┆            ┆ …          ┆ …          ┆   ┆      ┆ ain…      ┆ 5fd…      ┆ 512…      │
│ all_the_ne ┆ foxnews.co ┆ North      ┆ https://ww ┆ … ┆ en   ┆           ┆ 495dd2925 ┆ 41555e9ff │
│ ws         ┆ m          ┆ Carolina   ┆ w.foxnews. ┆   ┆      ┆ Ashley    ┆ 192ffab15 ┆ c490e1091 │
│            ┆            ┆ mom had    ┆ com/us/nor ┆   ┆      ┆ Ball is   ┆ 811617a55 ┆ de838985e │
│            ┆            ┆ kids br…   ┆ …          ┆   ┆      ┆ char…     ┆ 855…      ┆ 7c3…      │
│ all_the_ne ┆ thehill.co ┆ GOP        ┆ https://th ┆ … ┆ en   ┆ Republica ┆ 458d6100d ┆ 875b3fb97 │
│ ws         ┆ m          ┆ divided    ┆ ehill.com/ ┆   ┆      ┆ ns are    ┆ 814416b00 ┆ 520fd5c6c │
│            ┆            ┆ over care  ┆ business-a ┆   ┆      ┆ battling  ┆ da205d7c9 ┆ d00325248 │
│            ┆            ┆ for tran…  ┆ …          ┆   ┆      ┆ behin…    ┆ 13d…      ┆ ed5…      │
└────────────┴────────────┴────────────┴────────────┴───┴──────┴───────────┴───────────┴───────────┘

In [31]:
target_cols = [
    "article_id",
    "text_hash",
    "source_type",
    "domain",
    "title",
    "url",
    "datetime",
    "date",
    "author",
    "lang",
    "text",
]

df = (
    df.with_columns(
        pl.col("datetime").cast(pl.Datetime).alias("datetime"), 
        pl.col("datetime").cast(pl.Date).alias("date")
    )
    .select(target_cols)
)

In [36]:
DSN = "postgresql://narratives:narratives@localhost:5432/narratives"
table_name = "news_articles"

insert_sql = f"""
INSERT INTO {table_name} (
    {', '.join(target_cols)}
)
VALUES ({', '.join(['%s'] * len(target_cols))})
ON CONFLICT (article_id) DO NOTHING;
"""

n_total = df.height
n_inserted_est = 0
with psycopg.connect(DSN, autocommit=True) as conn:
    with conn.cursor() as cur:
        for chunk in df.select(target_cols).iter_slices(n_rows=5000):
            rows = list(chunk.rows())
            cur.executemany(insert_sql, rows)
            n_inserted_est += max(cur.rowcount or 0, 0)
            print(f"inserted_estimate={n_inserted_est/n_total * 100}%")
print(f"rows_in_df={n_total}")
print(f"inserted_estimate={n_inserted_est}")

inserted_estimate=0.1650264141278453%
inserted_estimate=0.3300528282556906%
inserted_estimate=0.4950792423835359%
inserted_estimate=0.6601056565113812%
inserted_estimate=0.8251320706392266%
inserted_estimate=0.9901584847670718%
inserted_estimate=1.1551848988949172%
inserted_estimate=1.3202113130227624%
inserted_estimate=1.4852377271506079%
inserted_estimate=1.6502641412784531%
inserted_estimate=1.8152905554062984%
inserted_estimate=1.9803169695341436%
inserted_estimate=2.145343383661989%
inserted_estimate=2.3103697977898343%
inserted_estimate=2.4753962119176793%
inserted_estimate=2.640422626045525%
inserted_estimate=2.8054490401733703%
inserted_estimate=2.9704754543012157%
inserted_estimate=3.1355018684290608%
inserted_estimate=3.3005282825569062%
inserted_estimate=3.4655546966847512%
inserted_estimate=3.6305811108125967%
inserted_estimate=3.7956075249404417%
inserted_estimate=3.960633939068287%
inserted_estimate=4.125660353196133%
inserted_estimate=4.290686767323978%
inserted_estimate=4.455713181451823%
inserted_estimate=4.620739595579669%
inserted_estimate=4.785766009707514%
inserted_estimate=4.950792423835359%
inserted_estimate=5.115818837963204%
inserted_estimate=5.28084525209105%
inserted_estimate=5.445871666218895%
inserted_estimate=5.6108980803467405%
inserted_estimate=5.775924494474586%
inserted_estimate=5.9409509086024315%
inserted_estimate=6.1059773227302765%
inserted_estimate=6.2710037368581215%
inserted_estimate=6.4360301509859665%
inserted_estimate=6.6010565651138124%
inserted_estimate=6.766082979241657%
inserted_estimate=6.9311093933695025%
inserted_estimate=7.0961358074973475%
inserted_estimate=7.261162221625193%
inserted_estimate=7.426188635753038%
inserted_estimate=7.5912150498808835%
inserted_estimate=7.75624146400873%
inserted_estimate=7.921267878136574%
inserted_estimate=8.086294292264421%
inserted_estimate=8.251320706392265%
inserted_estimate=8.416347120520111%
inserted_estimate=8.581373534647955%
inserted_estimate=8.746399948775801%
inserted_estimate=8.911426362903645%
inserted_estimate=9.076452777031491%
inserted_estimate=9.241479191159337%
inserted_estimate=9.406505605287183%
inserted_estimate=9.571532019415027%
inserted_estimate=9.736558433542873%
inserted_estimate=9.901584847670717%
inserted_estimate=10.066611261798563%
inserted_estimate=10.231637675926407%
inserted_estimate=10.396664090054255%
inserted_estimate=10.5616905041821%
inserted_estimate=10.726716918309945%
inserted_estimate=10.89174333243779%
inserted_estimate=11.056769746565635%
inserted_estimate=11.221796160693481%
inserted_estimate=11.386822574821325%
inserted_estimate=11.551848988949171%
inserted_estimate=11.716875403077017%
inserted_estimate=11.881901817204863%
inserted_estimate=12.046928231332707%
inserted_estimate=12.211954645460553%
inserted_estimate=12.376981059588397%
inserted_estimate=12.542007473716243%
inserted_estimate=12.707033887844087%
inserted_estimate=12.872060301971933%
inserted_estimate=13.03708671609978%
inserted_estimate=13.202113130227625%
inserted_estimate=13.367139544355469%
inserted_estimate=13.532165958483313%
inserted_estimate=13.69719237261116%
inserted_estimate=13.862218786739005%
inserted_estimate=14.027245200866851%
inserted_estimate=14.192271614994695%
inserted_estimate=14.357298029122543%
inserted_estimate=14.522324443250387%
inserted_estimate=14.687350857378231%
inserted_estimate=14.852377271506075%
inserted_estimate=15.017403685633923%
inserted_estimate=15.182430099761767%
inserted_estimate=15.347456513889613%
inserted_estimate=15.51248292801746%
inserted_estimate=15.677509342145305%
inserted_estimate=15.842535756273149%
inserted_estimate=16.007562170400995%
inserted_estimate=16.172588584528842%
inserted_estimate=16.337614998656687%
inserted_estimate=16.50264141278453%
inserted_estimate=16.667667826912375%
inserted_estimate=16.832694241040222%
inserted_estimate=16.997720655168067%
inserted_estimate=17.16274706929591%
inserted_estimate=17.327773483423755%
inserted_estimate=17.492799897551603%
inserted_estimate=17.657826311679447%
inserted_estimate=17.82285272580729%
inserted_estimate=17.98787913993514%
inserted_estimate=18.152905554062983%
inserted_estimate=18.31793196819083%
inserted_estimate=18.482958382318674%
inserted_estimate=18.64798479644652%
inserted_estimate=18.813011210574366%
inserted_estimate=18.97803762470221%
inserted_estimate=19.143064038830055%
inserted_estimate=19.308090452957902%
inserted_estimate=19.473116867085746%
inserted_estimate=19.63814328121359%
inserted_estimate=19.803169695341435%
inserted_estimate=19.968196109469282%
inserted_estimate=20.133222523597126%
inserted_estimate=20.29824893772497%
inserted_estimate=20.463275351852815%
inserted_estimate=20.628301765980662%
inserted_estimate=20.79332818010851%
inserted_estimate=20.958354594236354%
inserted_estimate=21.1233810083642%
inserted_estimate=21.288407422492046%
inserted_estimate=21.45343383661989%
inserted_estimate=21.618460250747734%
inserted_estimate=21.78348666487558%
inserted_estimate=21.948513079003426%
inserted_estimate=22.11353949313127%
inserted_estimate=22.278565907259114%
inserted_estimate=22.443592321386962%
inserted_estimate=22.608618735514806%
inserted_estimate=22.77364514964265%
inserted_estimate=22.938671563770498%
inserted_estimate=23.103697977898342%
inserted_estimate=23.26872439202619%
inserted_estimate=23.433750806154034%
inserted_estimate=23.598777220281878%
inserted_estimate=23.763803634409726%
inserted_estimate=23.92883004853757%
inserted_estimate=24.093856462665414%
inserted_estimate=24.25888287679326%
inserted_estimate=24.423909290921106%
inserted_estimate=24.58893570504895%
inserted_estimate=24.753962119176794%
inserted_estimate=24.91898853330464%
inserted_estimate=25.084014947432486%
inserted_estimate=25.24904136156033%
inserted_estimate=25.414067775688174%
inserted_estimate=25.579094189816022%
inserted_estimate=25.744120603943866%
inserted_estimate=25.90914701807171%
inserted_estimate=26.07417343219956%
inserted_estimate=26.239199846327406%
inserted_estimate=26.40422626045525%
inserted_estimate=26.569252674583094%
inserted_estimate=26.734279088710938%
inserted_estimate=26.899305502838782%
inserted_estimate=27.064331916966626%
inserted_estimate=27.229358331094478%
inserted_estimate=27.39438474522232%
inserted_estimate=27.559411159350166%
inserted_estimate=27.72443757347801%
inserted_estimate=27.889463987605858%
inserted_estimate=28.054490401733702%
inserted_estimate=28.219516815861546%
inserted_estimate=28.38454322998939%
inserted_estimate=28.54956964411724%
inserted_estimate=28.714596058245085%
inserted_estimate=28.87962247237293%
inserted_estimate=29.044648886500774%
inserted_estimate=29.209675300628618%
inserted_estimate=29.374701714756462%
inserted_estimate=29.539728128884306%
inserted_estimate=29.70475454301215%
inserted_estimate=29.86978095714%
inserted_estimate=30.034807371267846%
inserted_estimate=30.19983378539569%
inserted_estimate=30.364860199523534%
inserted_estimate=30.52988661365138%
inserted_estimate=30.694913027779226%
inserted_estimate=30.85993944190707%
inserted_estimate=31.02496585603492%
inserted_estimate=31.189992270162765%
inserted_estimate=31.35501868429061%
inserted_estimate=31.520045098418453%
inserted_estimate=31.685071512546298%
inserted_estimate=31.85009792667414%
inserted_estimate=32.01512434080199%
inserted_estimate=32.180150754929834%
inserted_estimate=32.345177169057685%
inserted_estimate=32.51020358318553%
inserted_estimate=32.67522999731337%
inserted_estimate=32.84025641144122%
inserted_estimate=33.00528282556906%
inserted_estimate=33.170309239696905%
inserted_estimate=33.33533565382475%
inserted_estimate=33.500362067952594%
inserted_estimate=33.665388482080445%
inserted_estimate=33.83041489620829%
inserted_estimate=33.99544131033613%
inserted_estimate=34.16046772446398%
inserted_estimate=34.32549413859182%
inserted_estimate=34.490520552719666%
inserted_estimate=34.65554696684751%
inserted_estimate=34.82057338097536%
inserted_estimate=34.985599795103205%
inserted_estimate=35.15062620923105%
inserted_estimate=35.31565262335889%
inserted_estimate=35.48067903748674%
inserted_estimate=35.64570545161458%
inserted_estimate=35.810731865742426%
inserted_estimate=35.97575827987028%
inserted_estimate=36.14078469399812%
inserted_estimate=36.305811108125965%
inserted_estimate=36.47083752225381%
inserted_estimate=36.63586393638166%
inserted_estimate=36.800890350509505%
inserted_estimate=36.96591676463735%
inserted_estimate=37.13094317876519%
inserted_estimate=37.29596959289304%
inserted_estimate=37.46099600702089%
inserted_estimate=37.62602242114873%
inserted_estimate=37.79104883527658%
inserted_estimate=37.95607524940442%
inserted_estimate=38.121101663532265%
inserted_estimate=38.28612807766011%
inserted_estimate=38.45115449178795%
inserted_estimate=38.616180905915805%
inserted_estimate=38.78120732004365%
inserted_estimate=38.94623373417149%
inserted_estimate=39.11126014829934%
inserted_estimate=39.27628656242718%
inserted_estimate=39.441312976555025%
inserted_estimate=39.60633939068287%
inserted_estimate=39.77136580481071%
inserted_estimate=39.936392218938565%
inserted_estimate=40.10141863306641%
inserted_estimate=40.26644504719425%
inserted_estimate=40.4314714613221%
inserted_estimate=40.59649787544994%
inserted_estimate=40.761524289577785%
inserted_estimate=40.92655070370563%
inserted_estimate=41.09157711783348%
inserted_estimate=41.256603531961325%
inserted_estimate=41.42162994608917%
inserted_estimate=41.58665636021702%
inserted_estimate=41.751682774344864%
inserted_estimate=41.91670918847271%
inserted_estimate=42.08173560260055%
inserted_estimate=42.2467620167284%
inserted_estimate=42.41178843085625%
inserted_estimate=42.57681484498409%
inserted_estimate=42.741841259111936%
inserted_estimate=42.90686767323978%
inserted_estimate=43.071894087367625%
inserted_estimate=43.23692050149547%
inserted_estimate=43.40194691562331%
inserted_estimate=43.56697332975116%
inserted_estimate=43.73199974387901%
inserted_estimate=43.89702615800685%
inserted_estimate=44.0620525721347%
inserted_estimate=44.22707898626254%
inserted_estimate=44.392105400390385%
inserted_estimate=44.55713181451823%
inserted_estimate=44.72215822864607%
inserted_estimate=44.887184642773924%
inserted_estimate=45.05221105690177%
inserted_estimate=45.21723747102961%
inserted_estimate=45.38226388515746%
inserted_estimate=45.5472902992853%
inserted_estimate=45.712316713413145%
inserted_estimate=45.877343127540996%
inserted_estimate=46.04236954166884%
inserted_estimate=46.207395955796684%
inserted_estimate=46.37242236992453%
inserted_estimate=46.53744878405238%
inserted_estimate=46.702475198180224%
inserted_estimate=46.86750161230807%
inserted_estimate=47.03252802643591%
inserted_estimate=47.197554440563756%
inserted_estimate=47.3625808546916%
inserted_estimate=47.52760726881945%
inserted_estimate=47.692633682947296%
inserted_estimate=47.85766009707514%
inserted_estimate=48.022686511202984%
inserted_estimate=48.18771292533083%
inserted_estimate=48.35273933945867%
inserted_estimate=48.51776575358652%
inserted_estimate=48.68279216771437%
inserted_estimate=48.84781858184221%
inserted_estimate=49.012844995970056%
inserted_estimate=49.1778714100979%
inserted_estimate=49.342897824225744%
inserted_estimate=49.50792423835359%
inserted_estimate=49.67295065248143%
inserted_estimate=49.83797706660928%
inserted_estimate=50.00300348073713%
inserted_estimate=50.16802989486497%
inserted_estimate=50.333056308992816%
inserted_estimate=50.49808272312066%
inserted_estimate=50.663109137248505%
inserted_estimate=50.82813555137635%
inserted_estimate=50.9931619655042%
inserted_estimate=51.158188379632044%
inserted_estimate=51.32321479375989%
inserted_estimate=51.48824120788773%
inserted_estimate=51.653267622015576%
inserted_estimate=51.81829403614342%
inserted_estimate=51.98332045027128%
inserted_estimate=52.14834686439912%
inserted_estimate=52.31337327852697%
inserted_estimate=52.47839969265481%
inserted_estimate=52.643426106782655%
inserted_estimate=52.8084525209105%
inserted_estimate=52.973478935038344%
inserted_estimate=53.13850534916619%
inserted_estimate=53.30353176329403%
inserted_estimate=53.468558177421876%
inserted_estimate=53.63358459154972%
inserted_estimate=53.798611005677564%
inserted_estimate=53.96363741980541%
inserted_estimate=54.12866383393325%
inserted_estimate=54.2936902480611%
inserted_estimate=54.458716662188955%
inserted_estimate=54.6237430763168%
inserted_estimate=54.78876949044464%
inserted_estimate=54.95379590457249%
inserted_estimate=55.11882231870033%
inserted_estimate=55.283848732828176%
inserted_estimate=55.44887514695602%
inserted_estimate=55.613901561083864%
inserted_estimate=55.778927975211715%
inserted_estimate=55.94395438933956%
inserted_estimate=56.108980803467404%
inserted_estimate=56.27400721759525%
inserted_estimate=56.43903363172309%
inserted_estimate=56.604060045850936%
inserted_estimate=56.76908645997878%
inserted_estimate=56.93411287410663%
inserted_estimate=57.09913928823448%
inserted_estimate=57.26416570236233%
inserted_estimate=57.42919211649017%
inserted_estimate=57.594218530618015%
inserted_estimate=57.75924494474586%
inserted_estimate=57.9242713588737%
inserted_estimate=58.08929777300155%
inserted_estimate=58.25432418712939%
inserted_estimate=58.419350601257236%
inserted_estimate=58.58437701538508%
inserted_estimate=58.749403429512924%
inserted_estimate=58.91442984364077%
inserted_estimate=59.07945625776861%
inserted_estimate=59.244482671896456%
inserted_estimate=59.4095090860243%
inserted_estimate=59.57453550015216%
inserted_estimate=59.73956191428%
inserted_estimate=59.90458832840785%
inserted_estimate=60.06961474253569%
inserted_estimate=60.234641156663535%
inserted_estimate=60.39966757079138%
inserted_estimate=60.564693984919224%
inserted_estimate=60.72972039904707%
inserted_estimate=60.89474681317492%
inserted_estimate=61.05977322730276%
inserted_estimate=61.22479964143061%
inserted_estimate=61.38982605555845%
inserted_estimate=61.554852469686296%
inserted_estimate=61.71987888381414%
inserted_estimate=61.884905297941984%
inserted_estimate=62.04993171206984%
inserted_estimate=62.214958126197686%
inserted_estimate=62.37998454032553%
inserted_estimate=62.545010954453375%
inserted_estimate=62.71003736858122%
inserted_estimate=62.87506378270906%
inserted_estimate=63.04009019683691%
inserted_estimate=63.20511661096475%
inserted_estimate=63.370143025092595%
inserted_estimate=63.53516943922044%
inserted_estimate=63.70019585334828%
inserted_estimate=63.86522226747613%
inserted_estimate=64.03024868160398%
inserted_estimate=64.19527509573182%
inserted_estimate=64.36030150985967%
inserted_estimate=64.52532792398752%
inserted_estimate=64.69035433811537%
inserted_estimate=64.8553807522432%
inserted_estimate=65.02040716637106%
inserted_estimate=65.1854335804989%
inserted_estimate=65.35045999462675%
inserted_estimate=65.51548640875458%
inserted_estimate=65.68051282288243%
inserted_estimate=65.84553923701027%
inserted_estimate=66.01056565113812%
inserted_estimate=66.17559206526596%
inserted_estimate=66.34061847939381%
inserted_estimate=66.50564489352165%
inserted_estimate=66.6706713076495%
inserted_estimate=66.83569772177734%
inserted_estimate=67.00072413590519%
inserted_estimate=67.16575055003304%
inserted_estimate=67.33077696416089%
inserted_estimate=67.49580337828873%
inserted_estimate=67.66082979241658%
inserted_estimate=67.82585620654442%
inserted_estimate=67.99088262067227%
inserted_estimate=68.15590903480012%
inserted_estimate=68.32093544892795%
inserted_estimate=68.4859618630558%
inserted_estimate=68.65098827718364%
inserted_estimate=68.8160146913115%
inserted_estimate=68.98104110543933%
inserted_estimate=69.14606751956718%
inserted_estimate=69.31109393369502%
inserted_estimate=69.47612034782287%
inserted_estimate=69.64114676195072%
inserted_estimate=69.80617317607857%
inserted_estimate=69.97119959020641%
inserted_estimate=70.13622600433426%
inserted_estimate=70.3012524184621%
inserted_estimate=70.46627883258995%
inserted_estimate=70.63130524671779%
inserted_estimate=70.79633166084564%
inserted_estimate=70.96135807497348%
inserted_estimate=71.12638448910133%
inserted_estimate=71.29141090322916%
inserted_estimate=71.45643731735701%
inserted_estimate=71.62146373148485%
inserted_estimate=71.7864901456127%
inserted_estimate=71.95151655974055%
inserted_estimate=72.1165429738684%
inserted_estimate=72.28156938799624%
inserted_estimate=72.4465958021241%
inserted_estimate=72.61162221625193%
inserted_estimate=72.77664863037978%
inserted_estimate=72.94167504450762%
inserted_estimate=73.10670145863547%
inserted_estimate=73.27172787276332%
inserted_estimate=73.43675428689116%
inserted_estimate=73.60178070101901%
inserted_estimate=73.76680711514685%
inserted_estimate=73.9318335292747%
inserted_estimate=74.09685994340254%
inserted_estimate=74.26188635753039%
inserted_estimate=74.42691277165822%
inserted_estimate=74.59193918578607%
inserted_estimate=74.75696559991393%
inserted_estimate=74.92199201404178%
inserted_estimate=75.08701842816961%
inserted_estimate=75.25204484229747%
inserted_estimate=75.4170712564253%
inserted_estimate=75.58209767055315%
inserted_estimate=75.74712408468099%
inserted_estimate=75.91215049880884%
inserted_estimate=76.07717691293668%
inserted_estimate=76.24220332706453%
inserted_estimate=76.40722974119237%
inserted_estimate=76.57225615532022%
inserted_estimate=76.73728256944806%
inserted_estimate=76.9023089835759%
inserted_estimate=77.06733539770376%
inserted_estimate=77.23236181183161%
inserted_estimate=77.39738822595945%
inserted_estimate=77.5624146400873%
inserted_estimate=77.72744105421513%
inserted_estimate=77.89246746834299%
inserted_estimate=78.05749388247082%
inserted_estimate=78.22252029659867%
inserted_estimate=78.38754671072653%
inserted_estimate=78.55257312485436%
inserted_estimate=78.71759953898221%
inserted_estimate=78.88262595311005%
inserted_estimate=79.0476523672379%
inserted_estimate=79.21267878136574%
inserted_estimate=79.37770519549359%
inserted_estimate=79.54273160962143%
inserted_estimate=79.70775802374929%
inserted_estimate=79.87278443787713%
inserted_estimate=80.03781085200498%
inserted_estimate=80.20283726613282%
inserted_estimate=80.36786368026067%
inserted_estimate=80.5328900943885%
inserted_estimate=80.69791650851636%
inserted_estimate=80.8629429226442%
inserted_estimate=81.02796933677205%
inserted_estimate=81.19299575089988%
inserted_estimate=81.35802216502773%
inserted_estimate=81.52304857915557%
inserted_estimate=81.68807499328342%
inserted_estimate=81.85310140741126%
inserted_estimate=82.01812782153911%
inserted_estimate=82.18315423566696%
inserted_estimate=82.34818064979481%
inserted_estimate=82.51320706392265%
inserted_estimate=82.6782334780505%
inserted_estimate=82.84325989217834%
inserted_estimate=83.00828630630619%
inserted_estimate=83.17331272043404%
inserted_estimate=83.33833913456188%
inserted_estimate=83.50336554868973%
inserted_estimate=83.66839196281757%
inserted_estimate=83.83341837694542%
inserted_estimate=83.99844479107325%
inserted_estimate=84.1634712052011%
inserted_estimate=84.32849761932894%
inserted_estimate=84.4935240334568%
inserted_estimate=84.65855044758463%
inserted_estimate=84.8235768617125%
inserted_estimate=84.98860327584033%
inserted_estimate=85.15362968996818%
inserted_estimate=85.31865610409602%
inserted_estimate=85.48368251822387%
inserted_estimate=85.64870893235171%
inserted_estimate=85.81373534647956%
inserted_estimate=85.9787617606074%
inserted_estimate=86.14378817473525%
inserted_estimate=86.30881458886309%
inserted_estimate=86.47384100299094%
inserted_estimate=86.63886741711877%
inserted_estimate=86.80389383124663%
inserted_estimate=86.96892024537448%
inserted_estimate=87.13394665950231%
inserted_estimate=87.29897307363017%
inserted_estimate=87.46399948775802%
inserted_estimate=87.62902590188585%
inserted_estimate=87.7940523160137%
inserted_estimate=87.95907873014156%
inserted_estimate=88.1241051442694%
inserted_estimate=88.28913155839724%
inserted_estimate=88.45415797252508%
inserted_estimate=88.61918438665293%