In [8]:
from src.pipeline.news_embedding import run_news_embeddings_transform_polars

In [9]:
from src.config import get_settings
import psycopg
from src.db_utils.pg_utils import select_query
import polars as pl

get_settings().postgres_dsn

'postgresql://narratives:narratives@localhost:5432/narratives'

In [10]:
run_news_embeddings_transform_polars(
    model_name="intfloat/multilingual-e5-small",
    # max_rows=100,
    normalize_embeddings=True,
    device="cpu"
)

[EMB_START] model=intfloat/multilingual-e5-small select_batch_size=2000 encode_batch_size=128 max_rows=None normalize=True

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[EMB_MODEL] embedding_dim=384
[EMB_DB] connected
[EMB_BATCH_START] batch=1 limit=2000 processed_so_far=0
[EMB_BATCH_ROWS] batch=1 rows=2000 non_empty_texts=2000

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

[EMB_BATCH_PAYLOAD] batch=1 payload_rows=2000 sample_article_id=005c2cd70dd5f82cd9bcc0f44217c8154c585be434ae6a7c705f5f2d307bf4f5
[EMB_BATCH_DONE] batch=1 batch_rows=2000 batch_upserted=2000 total_processed=2000 total_upserted=2000
[EMB_BATCH_START] batch=2 limit=2000 processed_so_far=2000
[EMB_BATCH_ROWS] batch=2 rows=2000 non_empty_texts=2000

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

[EMB_BATCH_PAYLOAD] batch=2 payload_rows=2000 sample_article_id=6d1a73791273b9549d8345548bc7088de9999fc9815cf877d10e5379d52300e7
[EMB_BATCH_DONE] batch=2 batch_rows=2000 batch_upserted=2000 total_processed=4000 total_upserted=4000
[EMB_BATCH_START] batch=3 limit=2000 processed_so_far=4000
[EMB_BATCH_ROWS] batch=3 rows=2000 non_empty_texts=2000

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

KeyboardInterrupt:

In [11]:
df = select_query('''
SELECT 
    news_embeddings.*,
    news_articles.title,
    news_articles.text
FROM news_embeddings
left join news_articles on news_embeddings.article_id = news_articles.article_id
    ''')
df

shape: (4_000, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ article_id     ┆ text_embedding ┆ model_name     ┆ updated_at    ┆ title         ┆ text          │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ list[f32]      ┆ str            ┆ datetime[μs,  ┆ str           ┆ str           │
│                ┆                ┆                ┆ Etc/UTC]      ┆               ┆               │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 005c2cd70dd5f8 ┆ [0.045111,     ┆ intfloat/multi ┆ 2026-05-05    ┆ Baby clothes  ┆ Baby clothes, │
│ 2cd9bcc0f44217 ┆ -0.009327, …   ┆ lingual-e5-sma ┆ 23:59:56.1899 ┆ and buckets:  ┆ razor blades  │
│ c8…            ┆ 0.0907…        ┆ ll             ┆ 40 UTC        ┆ Expo…         ┆ and…          │
│ 01c46c73811d0b ┆ [0.044665,     ┆ intfloat/multi ┆ 2026-05-05    ┆ CAF is        ┆ CAF is        │
│ 42547313f7725b ┆ -0.033415, …   ┆ lingual-e5-sma ┆ 23:59:56.1899 ┆ failing       ┆ failing       │
│ 50…            ┆ 0.0625…        ┆ ll             ┆ 40 UTC        ┆ Africa’s      ┆ Africa’s      │
│                ┆                ┆                ┆               ┆ World …       ┆ World …       │
│ 01c79b031f0410 ┆ [0.017892,     ┆ intfloat/multi ┆ 2026-05-05    ┆ «Гражданская  ┆ «Гражданская  │
│ 0a5ae245b2354e ┆ 0.006001, …    ┆ lingual-e5-sma ┆ 23:59:56.1899 ┆ платформа»    ┆ платформа»    │
│ e8…            ┆ 0.06283…       ┆ ll             ┆ 40 UTC        ┆               ┆ «Гражд…       │
│ 01f60346408103 ┆ [0.02037,      ┆ intfloat/multi ┆ 2026-05-05    ┆ Еврокомиссар  ┆ Еврокомиссар  │
│ 3306ccda450bd7 ┆ 0.012459, …    ┆ lingual-e5-sma ┆ 23:59:56.1899 ┆ сообщил о     ┆ сообщил о     │
│ 24…            ┆ 0.06255]       ┆ ll             ┆ 40 UTC        ┆ росте р…      ┆ росте р…      │
│ 024d7d476b509a ┆ [0.038403,     ┆ intfloat/multi ┆ 2026-05-05    ┆ Thierno Barry ┆ How did Guehi │
│ 1972d96d322c9c ┆ -0.006001, …   ┆ lingual-e5-sma ┆ 23:59:56.1899 ┆ and the       ┆ 'assist'      │
│ d5…            ┆ 0.0670…        ┆ ll             ┆ 40 UTC        ┆ offside …     ┆ allow B…      │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 7c53bb25ea1ddf ┆ [0.056142,     ┆ intfloat/multi ┆ 2026-05-06    ┆ Idac says cop ┆ The National  │
│ 206817db1a3f33 ┆ 0.00901, …     ┆ lingual-e5-sma ┆ 00:02:16.9323 ┆ arrests ‘by   ┆ Prosecuting   │
│ 88…            ┆ 0.031698…      ┆ ll             ┆ 97 UTC        ┆ the …         ┆ Autho…        │
│ 7cc6f3016dde20 ┆ [0.013122,     ┆ intfloat/multi ┆ 2026-05-06    ┆ Investigation ┆ A four-month  │
│ 6cb39265ed317e ┆ -0.045432, …   ┆ lingual-e5-sma ┆ 00:02:16.9323 ┆ fails to      ┆ Garda         │
│ f7…            ┆ 0.0434…        ┆ ll             ┆ 97 UTC        ┆ determi…      ┆ investigati…  │
│ 7ce0f0a0a80a27 ┆ [0.058676,     ┆ intfloat/multi ┆ 2026-05-06    ┆ By the 50th   ┆ By the 50th   │
│ 8353bdb7c6d031 ┆ -0.006273, …   ┆ lingual-e5-sma ┆ 00:02:16.9323 ┆ anniversary   ┆ anniversary   │
│ 94…            ┆ 0.0487…        ┆ ll             ┆ 97 UTC        ┆ of Lan…       ┆ of Lan…       │
│ 7ce1eda1cff605 ┆ [-0.000106,    ┆ intfloat/multi ┆ 2026-05-06    ┆ Govt says     ┆ 4 min readNew │
│ 6c551a1b348888 ┆ -0.004939, …   ┆ lingual-e5-sma ┆ 00:02:16.9323 ┆ adequate      ┆ DelhiUpdated: │
│ 44…            ┆ 0.075…         ┆ ll             ┆ 97 UTC        ┆ fertilizer …  ┆ Ma…           │
│ 7d0157253dd722 ┆ [-0.035535,    ┆ intfloat/multi ┆ 2026-05-06    ┆ На Дону       ┆ На Дону       │
│ 7f490ce6d4e988 ┆ -0.005616, …   ┆ lingual-e5-sma ┆ 00:02:16.9323 ┆ трудоустроено ┆ трудоустроено │
│ 64…            ┆ 0.040…         ┆ ll             ┆ 97 UTC        ┆ 16,9 тыс…     ┆ 16,9 тыс…     │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

### check closeness of news sample

In [12]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ids = df["article_id"].to_list()
X = np.vstack(df["text_embedding"].to_list())  # shape: (n, d)

S = cosine_similarity(X, X)
np.fill_diagonal(S, -1.0)  # exclude self-match

j = S.argmax(axis=1)

closest = pl.DataFrame({
    "article_id": ids,
    "closest_article_id": [ids[k] for k in j],
    "closest_similarity": S[np.arange(len(ids)), j],
})

In [13]:
closest.join(
    df.select(['article_id', 'title', 'text']), 
    on="article_id", 
    how="left"
).join(
    df.select(
        ['article_id', 
        pl.col('title').alias('closest_title')
        ]), 
    left_on="closest_article_id",   
    right_on="article_id", 
    how="left"
)

shape: (4_000, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ article_id     ┆ closest_articl ┆ closest_simila ┆ title         ┆ text          ┆ closest_title │
│ ---            ┆ e_id           ┆ rity           ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ ---            ┆ ---            ┆ str           ┆ str           ┆ str           │
│                ┆ str            ┆ f64            ┆               ┆               ┆               │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 005c2cd70dd5f8 ┆ 1adb0076df040a ┆ 0.895513       ┆ Baby clothes  ┆ Baby clothes, ┆ As a new      │
│ 2cd9bcc0f44217 ┆ e41f0e7207bdb7 ┆                ┆ and buckets:  ┆ razor blades  ┆ mother, the   │
│ c8…            ┆ 0b…            ┆                ┆ Expo…         ┆ and…          ┆ thought o…    │
│ 01c46c73811d0b ┆ 2281c203e2cb45 ┆ 0.901187       ┆ CAF is        ┆ CAF is        ┆ Red card for  │
│ 42547313f7725b ┆ bc79483f3d8ad1 ┆                ┆ failing       ┆ failing       ┆ players       │
│ 50…            ┆ 8a…            ┆                ┆ Africa’s      ┆ Africa’s      ┆ covering …    │
│                ┆                ┆                ┆ World …       ┆ World …       ┆               │
│ 01c79b031f0410 ┆ d99e1284d2db5c ┆ 0.828427       ┆ «Гражданская  ┆ «Гражданская  ┆ «Коммунисты   │
│ 0a5ae245b2354e ┆ 58391b1fb7e783 ┆                ┆ платформа»    ┆ платформа»    ┆ России»       │
│ e8…            ┆ 52…            ┆                ┆               ┆ «Гражд…       ┆               │
│ 01f60346408103 ┆ b275e351066caa ┆ 0.922084       ┆ Еврокомиссар  ┆ Еврокомиссар  ┆ ЕК: цены на   │
│ 3306ccda450bd7 ┆ 7290632e72051e ┆                ┆ сообщил о     ┆ сообщил о     ┆ газ в         │
│ 24…            ┆ 68…            ┆                ┆ росте р…      ┆ росте р…      ┆ Евросоюзе вы… │
│ 024d7d476b509a ┆ aeaffdd6299ce5 ┆ 0.888899       ┆ Thierno Barry ┆ How did Guehi ┆ Everton 3-3   │
│ 1972d96d322c9c ┆ 85cad8396fb438 ┆                ┆ and the       ┆ 'assist'      ┆ Man City:     │
│ d5…            ┆ 1e…            ┆                ┆ offside …     ┆ allow B…      ┆ Will 13 …     │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 7c53bb25ea1ddf ┆ 8bdb890f48c49d ┆ 0.902074       ┆ Idac says cop ┆ The National  ┆ South Africa  │
│ 206817db1a3f33 ┆ 3620b6ed9baa90 ┆                ┆ arrests ‘by   ┆ Prosecuting   ┆ president     │
│ 88…            ┆ 7d…            ┆                ┆ the …         ┆ Autho…        ┆ suspend…      │
│ 7cc6f3016dde20 ┆ 7fbedbe7c64d0a ┆ 0.909358       ┆ Investigation ┆ A four-month  ┆ Gardaí to     │
│ 6cb39265ed317e ┆ 1bf40b11428d4d ┆                ┆ fails to      ┆ Garda         ┆ deploy drones │
│ f7…            ┆ 13…            ┆                ┆ determi…      ┆ investigati…  ┆ for da…       │
│ 7ce0f0a0a80a27 ┆ 506a6bb597ebae ┆ 0.892969       ┆ By the 50th   ┆ By the 50th   ┆ Israeli       │
│ 8353bdb7c6d031 ┆ c652db33982459 ┆                ┆ anniversary   ┆ anniversary   ┆ settlers      │
│ 94…            ┆ f7…            ┆                ┆ of Lan…       ┆ of Lan…       ┆ block         │
│                ┆                ┆                ┆               ┆               ┆ Palesti…      │
│ 7ce1eda1cff605 ┆ 77e2ba00663b34 ┆ 0.878571       ┆ Govt says     ┆ 4 min readNew ┆ U.S. farmers  │
│ 6c551a1b348888 ┆ 38688e44d66f74 ┆                ┆ adequate      ┆ DelhiUpdated: ┆ plan to plant │
│ 44…            ┆ 2c…            ┆                ┆ fertilizer …  ┆ Ma…           ┆ les…          │
│ 7d0157253dd722 ┆ 59ef164a52f30a ┆ 0.863278       ┆ На Дону       ┆ На Дону       ┆ В             │
│ 7f490ce6d4e988 ┆ 8524ca5b69a258 ┆                ┆ трудоустроено ┆ трудоустроено ┆ Новороссийске │
│ 64…            ┆ 29…            ┆                ┆ 16,9 тыс…     ┆ 16,9 тыс…     ┆ выросла       │
│                ┆                ┆                ┆               ┆               ┆ числен…       │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘